<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20200821204839 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE developer (id INT AUTO_INCREMENT NOT NULL, name VARCHAR(255) NOT NULL, efficiency INT NOT NULL, PRIMARY KEY(id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('DROP TABLE developer');
    }

    public function postUp(Schema $schema): void
    {
        parent::postUp($schema); // TODO: Change the autogenerated stub

        $this->connection->insert('developer', ['name' => 'DEV1', 'efficiency' => 1]);
        $this->connection->insert('developer', ['name' => 'DEV2', 'efficiency' => 2]);
        $this->connection->insert('developer', ['name' => 'DEV3', 'efficiency' => 3]);
        $this->connection->insert('developer', ['name' => 'DEV4', 'efficiency' => 4]);
        $this->connection->insert('developer', ['name' => 'DEV5', 'efficiency' => 5]);
    }
}
